# Generated by Django 4.0.3 on 2022-04-01 22:28

from django.db import migrations, models
import user_manager.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[user_manager.validators.validate_email_domain]),
        ),
    ]
